<?php

/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.3
 */

/**
 * Database `products_compare`
 */

/* `products_compare`.`pages` */
$pages = array(
  array('name' => 'Home', 'path' => '', 'template' => 'public.page_templates.home', 'title' => 'Home', 'description' => 'Home page', 'content' => '<h1>Content</h1><p>U can change it <a href="/admin/pages/4/edit">here</a>&nbsp;</p>', 'status' => 'published'),
  array('name' => 'About us', 'path' => 'about_us', 'template' => 'public.page_templates.default', 'title' => 'About us', 'description' => 'PCMpare is an online store finder where you can find and compare product prices in online stores. Find where to buy cheaper and cheaper!', 'content' => '<h1>About us</h1><p>PCMpare is an online store finder where you can find and compare product prices in online stores. Find where to buy cheaper and cheaper!</p><p><strong>Search</strong>&nbsp;<br>You can find products from online stores by entering the name.</p><p>Some examples of how to use the finder:&nbsp;<br>&nbsp; &nbsp;search by model - mobile phone Apple iPhone 5, tablet Samsung Galaxy Note 10.1&nbsp;<br>&nbsp; &nbsp;search in the price range - LCD Monitors in the price of 120 Eur - 125 Eur&nbsp;<br>&nbsp; &nbsp;word exclusion search - Canon 240 HS IXUS black (finds only "Canon 240 HS IXUS" without the word "black" in the name)</p><p>When entering the search word, it does not matter whether it is written with or without length marks (CD player = CD player).</p><p><strong>Tops&nbsp;</strong><br>Information about the most searched products in the PCMpare system.&nbsp;</p><p><strong>Feedback&nbsp;</strong><br>The store review can be created by the buyer after making a purchase in the store from their own device.&nbsp;<br>You are only allowed to comment once about your own experience.&nbsp;<br>It is forbidden to post a review to participate in public competitions.&nbsp;<br>Users have the opportunity to post a review of the stores, indicating the rating and describing their experience.&nbsp;<br>It is forbidden to post false feedback.&nbsp;<br>It is forbidden to post a review for monetary or other consideration.&nbsp;<br>It is forbidden to post one review more than once from more than one account.&nbsp;<br>It is forbidden to post a review to participate in a public competition.&nbsp;<br>PCMpare is not responsible for the added reviews, as well as calls to do without rudeness and to observe the norms of courtesy and morality.&nbsp;<br>Reviews without explanation may be deleted or censored.&nbsp;</p><p><strong>Ratings&nbsp;</strong><br>Based on reviews, stores are rated 1 to 5 stars. In the calculation of the rating, newer reviews are considered to be more important, therefore they have an increased impact on the rating. The calculations also take into account the average referrals of other stores.&nbsp;</p><p><strong>Ranking of results&nbsp;</strong><br>Search results are sorted in ascending order by price. Depending on the search term or the quality of the results, the results may be sorted by relevance.&nbsp;<br>Content blocks marked Ad are not search results.&nbsp;</p><p><strong>Properties&nbsp;</strong><br>Company: SIA "Consultant"&nbsp;<br>Registration number: 40003835035&nbsp;<br>Legal address: Tallinn 33-4, Riga, LV-1012&nbsp;<br>salidzini@PCMpare</p>', 'status' => 'published'),
  array('name' => 'For shops', 'path' => 'for_shops', 'template' => 'public.page_templates.for_shops', 'title' => 'For shops', 'description' => 'PCMpare is the largest online search engine in Europe with 47,000 visitors per day and 1.3 million visitors per month.', 'content' => '<h1>For shops</h1><p>PCMpare is the largest online search engine in Europe with 47,000 visitors per day and 1.3 million visitors per month.</p><p>PCMpare maintains an up-to-date database of goods, updating information about stores and their assortments every day.</p><p>To learn how to add an online store to the PCMpare system, fill in this application form.</p><p><br>Terms for online stores:<br>  - Possibility to buy goods online and receive them in Europe<br>  - The payment and delivery process is described<br>  - PCMpare banner is placed on the main and / or product pages of the store<br>  - Created a catalog export XML file as described here<br>  - The store name and domain cannot be changed after registration<br>  - It is forbidden to post reviews about your store or for a fee, as well as from the device installed in the store<br>  - It is forbidden to hold public competitions with a call for comments<br>  - It is prohibited to abuse the PCMpare system, for example, by registering several stores with a similar assortment of goods, or by indicating one product several times<br>  - The store may be shut down if you receive a lot of complaints or suspect unfair commercial practices</p><p>XML file requirements:<br>  - The XML file shows the full price in EUR with VAT, for which an individual can purchase the product, including any additional costs<br>  - The XML file contains only goods with delivery times not exceeding 30 days<br>  - One item is specified only once in the XML file<br>  - The quantity of goods specified in the XML file in the warehouse is also indicated on the product description page of the store<br>  - The product and category names must correspond to the product, indicating the manufacturer and model of the product<br>  - The names must be concise in describing the appearance and functionality of the product and may not contain advertising texts such as "On site", "Free delivery", "Free credit"<br>  - Product links must be fully referenced to the registered domain<br>  - The image must describe the appearance of the product and must not be overlaid with the shop logo or other images which do not relate to the appearance of the product, as well as various additional inscriptions such as "On site", "Good product", "10 years on the market", " Gift "," 0% credit "etc.<br>  - If the product does not have an image that describes it, you must specify an empty value <image> </image><br>The XML file can be checked here</p>', 'status' => 'published'),
  array('name' => 'Privacy and cookie policy', 'path' => 'privacy_policy', 'template' => 'public.page_templates.default', 'title' => 'Privacy and cookie policy', 'description' => 'PCMpare collects information about user activities in order to provide better services to the users of the site.
When you sign in to your PCMpare account, your email address or social network profile link, as well as your browser and device information, are stored.', 'content' => '<h1>Privacy and cookie policy</h1><p><strong>Privacy</strong></p><p>Permission to use your data to show customized ads</p><p>PCMpare collects information about user activities in order to provide better services to the users of the site.<br>When you sign in to your PCMpare account, your email address or social network profile link, as well as your browser and device information, are stored.<br>&nbsp;</p><p><strong>Cookies</strong></p><p>In order for this website to work properly, we place cookies on your device.<br>What are cookies?</p><p>A cookie is a small text file that a website stores on your device. It helps the site remember your login and settings (such as language, font size, etc.).<br>How do we use cookies?</p><p>Cookies are used for the following purposes:</p><p>&nbsp; &nbsp;to personalize page content and ads<br>&nbsp; &nbsp;to track the flow of visitors<br>&nbsp; &nbsp;for user authorization with social media<br>&nbsp; &nbsp;to store the data used in the search<br>&nbsp; &nbsp;to store settings</p>', 'status' => 'published'),
);
